export const ERROR = "ERROR";

export const CREATE_PLAYER = "CREATE_PLAYER";
export const CREATE_GAME_ROOM = "CREATE_GAME_ROOM";
export const JOIN_GAME_ROOM = "JOIN_GAME_ROOM";
export const START_NEW_GAME = "START_NEW_GAME";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";